FROM python:3.11-slim

WORKDIR /app

COPY training /app/training
COPY core /app/core
COPY requirements.train.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

ENTRYPOINT ["python", "-m", "training.main"]
